name: Kate Text Highlight Plugin Build

on:
  push:
    branches:
      - master
  release:
    types: published
  workflow_dispatch:

jobs:
  check_commit_msg:
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.get_message.outputs.message }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit message
        id: get_message
        run: |
          echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')"
          echo "message=\"$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')\"" >> $GITHUB_ENV

  build:
    strategy:
      matrix:
        config:
          # - {
          #     qt_major_version: 5,
          #     qt_version: "5.15.2",
          #     arch: "gcc_64",
          #     qt_modules: "qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquick3d qtquicktimeline qtscript qtvirtualkeyboard qtwaylandcompositor qtwebengine qtwebglplugin",
          #     ecm_branch: "kf5",
          #   }
          - { qt_major_version: 6 }

    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --user root --privileged
    env:
      QT_MAJOR_VERSION: ${{ matrix.config.qt_major_version }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pacman -Syyu --noconfirm
          pacman -S git curl python base-devel wget cmake ninja kate extra-cmake-modules --noconfirm

      - name: Build Plugin
        run: |
          mkdir build
          cd build
          cmake .. \
            -DQT_MAJOR_VERSION=${{ env.QT_MAJOR_VERSION }} \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: text-highlight-plugin-${{ github.sha }}.so
          path: build/bin/kf${{ env.QT_MAJOR_VERSION }}/ktexteditor/text-highlight-plugin.so
      - name: Upload Artifact to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/kf${{ env.QT_MAJOR_VERSION }}/ktexteditor/text-highlight-plugin.so
          tag: ${{ github.ref }}
          overwrite: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
      #   with:
      #     limit-access-to-actor: false
